name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_call:

jobs:
  test:
    name: Test the package
    uses: ./.github/workflows/_test.yaml
    with:
      python-version: '3.10'
